### ISSUE TITLE
The rate limit `period` appears to be a `frequency` (inverted logic)

### ISSUE THREAD

**Issue by paulfurley** [tomasbasham/ratelimit#1]
Hi, I just scratched my head over this for a while then I made the following simple test:

```python
import datetime

from ratelimit import rate_limited


@rate_limited(2)
def rate_limited_function():
    print("function called at: {}".format(datetime.datetime.now()))

if __name__ == '__main__':
    while True:
        rate_limited_function()
```

which produces the following output:

```
function called at: 2017-02-02 12:51:00.969778
function called at: 2017-02-02 12:51:01.470701
function called at: 2017-02-02 12:51:01.971523
function called at: 2017-02-02 12:51:02.472208
function called at: 2017-02-02 12:51:02.972889
function called at: 2017-02-02 12:51:03.473723
```
e.g. the it's rate limiting the function call to once every 0.5 seconds, not once every 2 seconds.

conversely, passing a period of `0.5` runs the function every 2 seconds: (and curiously it doesn't do the first call for 2 seconds)

```
function called at: 2017-02-02 12:58:56.494749
function called at: 2017-02-02 12:58:58.496957
function called at: 2017-02-02 12:59:00.499353
function called at: 2017-02-02 12:59:02.501679
```

The README says "The argument passed into the decorator imposes the time that must elapse before a method can be called again." and the argument is called `period` so I believe passing `period=2` is supposed to mean "no more than every 2 seconds". But seemingly the logic is inverted.

There's a very simple, thread safe, [imer-based approach you might like to consider at [http://stackoverflow.com/questions/30918772/rate-limiting-python-decorator/30918773#30918773](http://stackoverflow.com/questions/30918772/rate-limiting-python-decorator/30918773#30918773)

**Comment by tomasbasham** [comment]
Thanks for pointing this out. Definitely a faux pas. I'll take a look at this tomorrow

**Comment by tomasbasham** [comment]
So I went through the code this afternoon. The confusion comes from my poorly written README. I even spent an hour scratching my head. I have now updated the code; placing some error checking, comments and sensible defaults.

I'll explain the example you posted a little better:

```
from ratelimit import rate_limited
import datetime

@rate_limited(2)
def rate_limited_function():
    print("function called at: {}".format(datetime.datetime.now()))

if __name__ == '__main__':
    while True:
        rate_limited_function()
```

So to clarify, the arguments of the decorator are to be read as run the `rate_limited_function` function at most twice per second. You may also pass in a second argument that can change the time window.

```
from ratelimit import rate_limited
import datetime

@rate_limited(8, 2.5)
def rate_limited_function():
    print("function called at: {}".format(datetime.datetime.now()))
```

This therefore reads as run the `rate_limited_function` function at most six times every 2.5 seconds. If you ran the method on every iteration of an infinite loop you should see the method being called every ~0.3125 seconds.

I hope this makes sense.

**Comment by paulfurley** [comment]
Thanks for this, @tomasbasham !
