### ISSUE TITLE
Use monotonic time when available

### ISSUE THREAD

**Issue by joell** [tomasbasham/ratelimit#11]
https://github.com/tomasbasham/ratelimit/blob/fcdead12d0e90741fb04f391409b4dee04804207/ratelimit/__init__.py#L48

When using `time.time()`, algorithms like rate limiting are susceptible to violent changes to the system clock, including things like the system time moving backwards.  It turns out the system clock is a [lot less](http://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time) [reliable](http://infiniteundo.com/post/25509354022/more-falsehoods-programmers-believe-about-time) than we often presume.  Examples of this can be from things like VMs being resumed from suspension and correcting their clock, to NTP making large clock adjustments, to UTC leap seconds.

In Python 3.3, a [`time.monotonic`](https://docs.python.org/3/library/time.html#time.monotonic) function was introduced, and in Python 3.5, it was made available on all platforms.  This function will use the system monotonic clock, which -- while not suitable for algorithms that make calendar computations -- works reliably for algorithms making time-offset computations, such as rate limiting.  It has the advantage of avoiding some of the worst of the system clock changes I mentioned above, thereby making rate limiting more reliable.

My suggestion would be to do a check just after module imports for the `time.monotonic` function if it is available and to use it if it is; possibly something like this at the top of the module:
```python
import time
get_time = time.monotonic if hasattr(time, 'monotonic') else time.time
```

**Comment by tomasbasham** [comment]
This was a great idea. I have incorporated this within the changes I have made to the project. https://github.com/tomasbasham/ratelimit/tree/2.0
