### ISSUE TITLE
Running once in x time instead of up to y times in x time

### ISSUE THREAD

**Issue by rola93** [tomasbasham/ratelimit#15]
Just to clarify, let me show an example: wheen you set it up for 10 calls in 100 seconds, it lets you call it once every ten seconds, which is not exactly the same. See the following example:

```
>>> from ratelimit import rate_limited
>>> import datetime
>>> import time
>>> @rate_limited(10,100)
... def test(i=1):
...     ts = time.time()
...     st = datetime.datetime.fromtimestamp(ts).strftime('%H:%M:%S')
...     print("{}::  {}".format(i, st))
... 
>>> for i in range(12):
...     test()
... 
1::  12:14:05
1::  12:14:15
1::  12:14:25
1::  12:14:35
1::  12:14:45
1::  12:14:55
1::  12:15:05
1::  12:15:15
1::  12:15:25
1::  12:15:35
1::  12:15:45
1::  12:15:55
>>>


```

I was expecting test() function to be called 10 times and then be blocked, but instead, there is only one call in 10 seconds. Is there a way to get the behaviour I'm expecting?

Thanks in advance

**Comment by tomasbasham** [comment]
Hi, what you're experiencing was the intentional behaviour when I first wrote this repo. However I'm looking to soon update this repo to behave like you were expecting. Hopefully I can get onto this within the next week

**Comment by rola93** [comment]
Thenks for your answer!

I finally implemented this as follows (perhaps this is useful for your implementation):
`

class ApiCaller(object):

    def __init__(self, n_calls: int, s_seconds: int):

        self.api_calls = []  # Queue of timestamps were calls have been authorised
        self.lock_for_api_calls = Lock()  # Lock to ensure that there is only one thread operating on the queue
        self.api_calls_counter = 0 # Counter of authorised API calls
        self.n_calls = n_calls # Max number of calls admited in s_seconds
        self.s_seconds = s_seconds # Time in seconds considered

    def let_me_call_the_api(self, lock: bool=False) -> bool:
        """
        Allows or deny threads to call the API, as far as no more than n_calls are made in last s_seconds.
        If this limit is not respected, the thread will lock untill the call can be made.
        If lock == True, the thread will not be locked, but the result must be checked.
        The order of API calls may not be respected.
        :param: lock: whether or not lock the current thread when rate is superated
        :return: True iff the thread can call the API. When lock=False, you don't need to check for the result
        """
        # Lock the queue
        self.lock_for_api_calls.acquire()

        if len(self.api_calls) < self.n_calls:
            # Si aun no se hicieron los 600 pedidos, agregamos a la cola la hora en que se 'pidio permiso'
            # If there has not been more than self.n_calls,
            # we add to the queue the timestamp at authorization was required
            self.api_calls.append(datetime.now())
            # increment the api calls counter
            self.api_calls_counter += 1
            # release the queue
            self.lock_for_api_calls.release()
            return True
        else:
            # save timestamp at which authorization was required
            ts = datetime.now()
            if (ts - self.api_calls[self.api_calls_counter % self.n_calls]).seconds > self.s_seconds:
                # If there has been more than self.s_seconds since the last self.n_calls
                # save authorisation timestamp in the queue
                self.api_calls[self.api_calls_counter % self.n_calls] = ts
                # increment the api calls counter
                self.api_calls_counter += 1
                # release the queue
                self.lock_for_api_calls.release()
                return True
            else:
                if not lock:
                    # since there haven't been time enough, and we don't want to be locked,
                    # release the queue and return
                    self.lock_for_api_calls.release()
                    return False
                # If there has NOT been more than self.s_seconds since the last self.n_calls
                # calculate time needed to next authorization plus one second (there may be rounding errors)
                sleep_time = (ts - self.api_calls[self.api_calls_counter % 600]).seconds + 1
                # release the queue
                self.lock_for_api_calls.release()
                # go to sleep calculated time
                time.sleep(sleep_time)
                # after that time, we ask for authorization again
                return self.let_me_call_the_api()
`

feel free to use it, hope it helps, and its nice to know that this project is alive!

**Comment by tomasbasham** [comment]
I went for a slightly different approach in the end that changes the way this project works. Now instead of splitting up a time period and sleeping until the next call can be made the decorator allows for the maximum number of method invocations over a time window and raises an exception if the max calls is exceeded. This is then reset when the time window expires. I coudl really use your feedback. Does this make more sense https://github.com/tomasbasham/ratelimit/tree/2.0

**Comment by tomasbasham** [comment]
Instead of making the `limits` decorator schedule calls when the rate limit has been reached I have implemented a second decorator. This decorator implements a retry strategy that mirrors the behaviour provided by earlier versions of this package.

I felt that the `limits` decorator should not force users of this package to always use the same retry strategy but instead allow them to customise it. Hopefully you agree that providing this customisation makes the package more useful, whilst still being able to use the package similar to before (with some minor code changes).
