### ISSUE TITLE
Return error instead of waiting

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [tomasbasham/ratelimit#16]
This is a feature request.

It would be great, if there was a way to return an error, if there are too many calls of the limited function, instead of simply waiting and still doing the requested thing later. Perhaps a third parameter in the decorator, which takes an error class?

**Comment by tomasbasham** [comment]
Thank you for the suggestion. I'm really glad for the feedback. I intend on rewriting this package very shortly to accommodate all the other suggestions that have been made. I will look into this one too

**Comment by tomasbasham** [comment]
Hi. I have been working through most of the issues on this project. Do you think this implementation makes more sense https://github.com/tomasbasham/ratelimit/tree/2.0

**Comment by ZelphirKaltstahl** [comment]
@tomasbasham Hey, I found some library that already does what I needed (sorry, I needed it rather quickly^^) and maybe you could take bits from it to add to your library: https://github.com/piotrmaslanka/falcon-ratelimit/blob/master/falconratelimit/ratelimit.py#L40 There the raising function is wrapped and it is used as a decorator in the end.

Anyway I (re?-)learned something about decorators which I memorized as follows:

* when wrapping the functions about the wrap depths:
  * 1. level takes the parameters of the decorator
  * 2. level takes the original function which will be decorated
  * 3. level is the decorated function that will be returned (iirc)

I ended up modifying the decorator that the other project has and created a pull request to return correct HTTP status code.

I can take a look at your new version soon I hope.

**Comment by tomasbasham** [comment]
I understand I took some time to getting around to fixing some of the issues with this project. Thank you for your suggestions and the above link
