### ISSUE TITLE
First call is blocked.

### ISSUE THREAD

**Issue by mangodan2003** [tomasbasham/ratelimit#2]
As mentioned in https://github.com/tomasbasham/ratelimit/issues/1 - the first call gets blocked.

**Comment by mangodan2003** [comment]
I see what is happening here - it's not blocked altogether, it just doesn't work quite as I had expected

if i use 

@rate_limited(1,10)
def Test(self):
  print('Test')

to limit to 1 call in 10 seconds 

and call Test once, it doesn't actually happen until the 10 seconds has elapsed.

**Comment by tomasbasham** [comment]
That is an interesting suggestion. I will take a look this evening. Thansk

**Comment by tomasbasham** [comment]
The decorator now throws an exception once the limit has been reached. Thank you for the suggestions.
