### ISSUE TITLE
Accept arg for exponential backoff on retries

### ISSUE THREAD

**Issue by stevenwu4** [tomasbasham/ratelimit#21]
Some APIs, like Lever, recommend/request for exponential backoff

https://hire.lever.co/developer/documentation#rate-limits

**Comment by tomasbasham** [comment]
This repo does not intend to implement retry strategies as there are many examples of this elsewhere. Instead you can augment the decorator (decorate the decorator). I recommend the one mentioned here https://github.com/tomasbasham/ratelimit#usage. I have used this in the past and it worked well for me. Let me know if it causes you issues
