### ISSUE TITLE
caller is also blocked?

### ISSUE THREAD

**Issue by mangodan2003** [tomasbasham/ratelimit#3]
Consider the following :
```
from ratelimit import *
from time import sleep
import datetime

class Foo(object):
  def A(self):
    print('A called at {}'.format(datetime.datetime.now()))
    self.B()

  @rate_limited(1,10)
  def B(self):
    print('B called at {}'.format(datetime.datetime.now()))


foo = Foo()

while True:
  foo.A()
  sleep(1)
```

I don't think this behaves as intended?
```
python2 testratelimit.py 
A called at 2017-05-10 21:47:26.014120
B called at 2017-05-10 21:47:35.957787
A called at 2017-05-10 21:47:36.958130
B called at 2017-05-10 21:47:46.960392
A called at 2017-05-10 21:47:47.961745
```

Oh, maybe the call to B is limited by sleeping rather than just doesn't happen - this makes more sense come to think of it - just not what i needed. nevermind.

**Comment by tomasbasham** [comment]
This project has been reimplemented such that a maximum number of calls can be made within a given time window, after which an exception is raised. The number of calls is reset once the time window has expired. I will close this now as I believe this issue to be addressed within the changes
