### ISSUE TITLE
Multiprocess aware rate limit - Redis or Django DB backend ?

### ISSUE THREAD

**Issue by stuaxo** [tomasbasham/ratelimit#41]
It would be good if ratelimit could store it's ratelimit somewhere like Redis or the database, this would make it more useful under Django, where there can be more than one process running.

**Comment by konstunn** [comment]
Indeed!

**Comment by stuaxo** [comment]
I think this would be a seperate project that could hook into this.

I'm going to close this, as I'm not going to get time to implement it , and likely to finish work on the current project that uses RateLimit.
