### ISSUE TITLE
Concurrency issues

### ISSUE THREAD

**Issue by ginward** [tomasbasham/ratelimit#9]
I noticed the code [here](https://github.com/tomasbasham/ratelimit/blob/1f921dedc8286363e5c355ba0188b6ed6a95b740/ratelimit/__init__.py#L40-L46) has been changed since my [last commit](https://github.com/tomasbasham/ratelimit/blob/ea16e71bb635499ff5701f20817391fda246ed94/ratelimit/__init__.py#L32-L38). 

I do realize that my version will probably block 2 or more threads from accessing the API call at the same time, thus compromising my intention of multithreading. However, it seems that the new code might have issues on that subject too.

            with lock:
                elapsed = time.time() - last_called[0]
            left_to_wait = frequency - elapsed
            if left_to_wait > 0:
                time.sleep(left_to_wait)
            ret = func(*args, **kargs)
            last_called[0] = time.time()
            return ret

The above code only locks the operation `elapsed = time.time() - last_called[0]`, but not the operation `last_called[0] = time.time()`. Now, for example, if `func` call is an operation that blocks for 20 seconds (maybe due to slow API communications), and my frequency is 1 second, and I have 10 threads at the same time. What is going to happen?

The first thread will acquire the lock, calculate the elapsed, release the lock, run `func`, which will block for 20 seconds. Note that last_called[0] will not be updated during the 20 seconds! Therefore, during the 20 seconds, all of my other 9 threads will be able to acquire and release the lock, call func. If more than 2 threads call `func` in one second, the effect of the rate limiter will be compromised. 

Therefore, I propose the [change](https://github.com/tomasbasham/ratelimit/pull/8). 

Note that I [moved](https://github.com/ginward/ratelimit/blob/0505cdb0f687b3b9f60923672462a598a7dfc043/ratelimit/__init__.py#L41-L45) the last_called[0] within the lock structure. The advantage is that if func blocks for a bit, the threads won't block. 

I tested the code with the following code: 
```
import time
import threading
@rate_limited(2, 1)
def increment():
    '''
    Increment the counter at most twice every second.
    '''
    time.sleep(5)
    print time.time()

thread1 = threading.Thread(target = increment)
thread2 = threading.Thread(target = increment)
thread3 = threading.Thread(target = increment)

thread1.start()
thread2.start()
thread3.start()
```
The output of the [old commit](https://github.com/tomasbasham/ratelimit/blob/1f921dedc8286363e5c355ba0188b6ed6a95b740/ratelimit/__init__.py) is: 

`1502028965.591502028965.591502028965.59`

The output of my [new commit](https://github.com/ginward/ratelimit/blob/0505cdb0f687b3b9f60923672462a598a7dfc043/ratelimit/__init__.py) is: 

```
1502029318.34
1502029318.84
1502029319.35
```
Apparently, all three threads called the same function at the same seconds in the old commit, which broke the limit. While the new commit ensures the limit.

**Comment by tomasbasham** [comment]
Sorry this was a bad refactoring on my part. Thanks for pointing this out. I'll merge this is ASAP

**Comment by ginward** [comment]
No worries. There was problem in my previous code too, and you helped me realize that.
